import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          <Image src='/pethub.svg' height={70} width={70}></Image>
          <h2>Pet<span>Hub</span></h2>
        </h1>
        <Image src='/welcome.svg' height={250} width={250}></Image>
        <h2>Welcome to PetHub</h2>
        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eum ut vero omnis vel distinctio aut deleniti illo fuga praesentium repellendus!</p>
        <button className='btn-primary' style={{width: "15rem", marginBottom: "0.8rem"}}>Get started</button>
        <button className="btn-secondary" style={{width: "15rem"}}>Sign In</button>
      </main>
    </div>
  )
}

export default Home
